In [42]:
import folium
import pandas as pd
import numpy as np
import os
from geopy.geocoders import Nominatim
from pyzillow.pyzillow import ZillowWrapper, GetDeepSearchResults, ZillowError, GetUpdatedPropertyDetails

geolocator = Nominatim(user_agent="my-application")

In [2]:
dashdf = pd.DataFrame(columns=['Address', 'Zipcode', 'zEstimate', 'Home Type', 'Property Size', 'Home Size', 'Bedrooms', 'Bathrooms', 'Last Sold Price', 'Last Sold Date', 'Latitude', 'Longitude', 'zEst Last Updated'])
dashdf

Empty DataFrame
Columns: [Address, Zipcode, zEstimate, Home Type, Property Size, Home Size, Bedrooms, Bathrooms, Last Sold Price, Last Sold Date, Latitude, Longitude, zEst Last Updated]
Index: []

In [4]:
dashdf.Address = ['5250 Berkshire, Detroit', 
           '5210 Berkshire, Detroit', 
           '15864 Manning, Detroit',
           '16083 Manning, Detroit',
          '3346 Webb, Detroit',
          '19662 McCormick, Detroit',
          '4700 Haverhill, Detroit',
          ' 4836 Haverhill, Detroit',
          '20215 Spencer, Detroit',
          '20179 Spencer, Detroit',
          '3442 Pennsylvania, Detroit',
          '134 Worcester, Detroit',
          '8911 Mendota, Detroit',
          '11790 Wilshire, Detroit']
dashdf.Zipcode = ['48224',
 '48224',
 '48205',
 '48205',
 '48206',
 '48224',
 '48224',
 '48224',
 '48234',
 '48234',
 '48214',
 '48203',
 '48204',
 '48213']

In [11]:
for i in range(0,len(dashdf)):
    zillow_data = ZillowWrapper('X1-ZWz1guvg85e1or_9fxlx')
    deep_search_response = zillow_data.get_deep_search_results(dashdf.Address[i],dashdf.Zipcode[i])
    result = GetDeepSearchResults(deep_search_response)
    dashdf.zEstimate[i] = result.zestimate_amount
    dashdf["Home Type"][i] = result.home_type
    dashdf["Property Size"][i] = result.property_size
    dashdf["Home Size"][i] = result.home_size
    dashdf["Bedrooms"][i] = result.bedrooms
    dashdf["Bathrooms"][i] = result.bathrooms
    dashdf["Last Sold Price"][i] = result.last_sold_price
    dashdf["Last Sold Date"][i] = result.last_sold_date
    dashdf["Latitude"][i] = result.latitude
    dashdf["Longitude"][i] = result.longitude

dashdf.Latitude = dashdf.Latitude.astype(float)
dashdf.Longitude = dashdf.Longitude.astype(float)

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
dashdf

,Address,Zipcode,zEstimate,Home Type,Property Size,Home Size,Bedrooms,Bathrooms,Last Sold Price,Last Sold Date,Latitude,Longitude,zEst Last Updated
0,"5250 Berkshire, Detroit",48224,31850,SingleFamily,4356,1294,3,1.0,25000,2018-07-19,42.403082,-82.945927,NaN
1,"5210 Berkshire, Detroit",48224,29544,SingleFamily,4356,1136,3,2.0,31000,2018-08-14,42.402598,-82.945789,NaN
2,"15864 Manning, Detroit",48205,34951,SingleFamily,5227,773,3,1.0,18000,2018-08-13,42.440721,-82.956940,NaN
3,"16083 Manning, Detroit",48205,23521,SingleFamily,4356,705,2,1.0,21000,2018-08-13,42.441278,-82.954185,NaN
4,"3346 Webb, Detroit",48206,31455,SingleFamily,4791,1250,3,2.0,10900,2010-03-18,42.380085,-83.123168,NaN
5,"19662 McCormick, Detroit",48224,31025,SingleFamily,4617,696,None,1.0,25000,2018-08-13,42.429946,-82.939787,NaN
6,"4700 Haverhill, Detroit",48224,25924,SingleFamily,4791,1334,None,1.5,None,NaT,42.399382,-82.941168,NaN
7,"4836 Haverhill, Detroit",48224,34585,SingleFamily,4574,1237,None,1.0,21500,2010-05-19,42.400237,-82.941728,NaN
8,"20215 Spencer, Detroit",48234,35554,SingleFamily,4051,953,None,2.0,21351,1994-11-23,42.445258,-83.027361,NaN
9,"20179 Spencer, Detroit",48234,29395,SingleFamily,3920,940,3,1.0,5000,2015-11-20,42.444778,-83.027342,NaN
10,"3442 Pennsylvania, Detroit",48214,14190,SingleFamily,2875,635,None,1.0,None,NaT,42.371651,-82.990376,NaN
11,"134 Worcester, Detroit",48203,21365,SingleFamily,5000,1264,None,1.0,35000,2007-03-16,42.422962,-83.104459,NaN
12,"8911 Mendota, Detroit",48204,35624,SingleFamily,4356,1368,4,1.0,11000,2014-12-05,42.360430,-83.164384,NaN
13,"11790 Wilshire, Detroit",48213,35594,SingleFamily,5662,1659,4,2.0,5000,2008-06-10,42.405660,-82.990299,NaN

In [8]:
dashdf["Last Sold Date"] = pd.to_datetime(dashdf["Last Sold Date"], format = "%m/%d/%Y", errors = 'coerce')

In [9]:
dashdf

,Address,Zipcode,zEstimate,Home Type,Property Size,Home Size,Bedrooms,Bathrooms,Last Sold Price,Last Sold Date,Latitude,Longitude,zEst Last Updated
0,"5250 Berkshire, Detroit",48224,31850,SingleFamily,4356,1294,3,1.0,25000,2018-07-19,42.403082,-82.945927,NaN
1,"5210 Berkshire, Detroit",48224,29544,SingleFamily,4356,1136,3,2.0,31000,2018-08-14,42.402598,-82.945789,NaN
2,"15864 Manning, Detroit",48205,34951,SingleFamily,5227,773,3,1.0,18000,2018-08-13,42.440721,-82.95694,NaN
3,"16083 Manning, Detroit",48205,23521,SingleFamily,4356,705,2,1.0,21000,2018-08-13,42.441278,-82.954185,NaN
4,"3346 Webb, Detroit",48206,31455,SingleFamily,4791,1250,3,2.0,10900,2010-03-18,42.380085,-83.123168,NaN
5,"19662 McCormick, Detroit",48224,31025,SingleFamily,4617,696,None,1.0,25000,2018-08-13,42.429946,-82.939787,NaN
6,"4700 Haverhill, Detroit",48224,25924,SingleFamily,4791,1334,None,1.5,None,NaT,42.399382,-82.941168,NaN
7,"4836 Haverhill, Detroit",48224,34585,SingleFamily,4574,1237,None,1.0,21500,2010-05-19,42.400237,-82.941728,NaN
8,"20215 Spencer, Detroit",48234,35554,SingleFamily,4051,953,None,2.0,21351,1994-11-23,42.445258,-83.027361,NaN
9,"20179 Spencer, Detroit",48234,29395,SingleFamily,3920,940,3,1.0,5000,2015-11-20,42.444778,-83.027342,NaN
10,"3442 Pennsylvania, Detroit",48214,14190,SingleFamily,2875,635,None,1.0,None,NaT,42.371651,-82.990376,NaN
11,"134 Worcester, Detroit",48203,21365,SingleFamily,5000,1264,None,1.0,35000,2007-03-16,42.422962,-83.104459,NaN
12,"8911 Mendota, Detroit",48204,35624,SingleFamily,4356,1368,4,1.0,11000,2014-12-05,42.36043,-83.164384,NaN
13,"11790 Wilshire, Detroit",48213,35594,SingleFamily,5662,1659,4,2.0,5000,2008-06-10,42.40566,-82.990299,NaN

In [ ]:
dash

In [14]:
#creating a map object centered on the mean coordinates values
dashmap = folium.Map(location=[np.mean(dashdf.Latitude), np.mean(dashdf.Longitude)], zoom_start=12)

#for loop that will place our markers 
for i in range(0,len(dashdf)):
    pop=dashdf['Address'][i]
    folium.Marker([dashdf.iloc[i]['Latitude'], dashdf.iloc[i]['Longitude']], popup=dashdf.iloc[i]['Address']).add_to(dashmap)

#dashmap
#dashmap.save('bauhaus.html')

In [16]:
#PARCEL MAP DATASET
parceldf = pd.read_csv("./data/PARCELS.csv")

trimmedcols = ['parcelnum', 'address', 'zip_code', 'year_built', 'zoning', 'land_value', 'owner1', 'last_sale_', 'last_sal_1']
db = parceldf[trimmedcols]
db['zEstimate'] = np.nan
db['Home Type'] = np.nan
db['Property Size'] = np.nan 
db['Home Size'] = np.nan
db['Bedrooms'] = np.nan 
db['Bathrooms'] = np.nan
db['Last Sold Price'] = np.nan 
db['Last Sold Date'] = np.nan
db['Latitude'] = np.nan
db['Longitude'] = np.nan

/Users/Brenn/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (6,22,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [18]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381608 entries, 0 to 381607
Data columns (total 19 columns):
parcelnum          381604 non-null object
address            381500 non-null object
zip_code           375669 non-null object
year_built         381507 non-null float64
zoning             376953 non-null object
land_value         381507 non-null float64
owner1             381505 non-null object
last_sale_         381507 non-null float64
last_sal_1         279691 non-null object
zEstimate          0 non-null float64
Home Type          0 non-null float64
Property Size      0 non-null float64
Home Size          0 non-null float64
Bedrooms           0 non-null float64
Bathrooms          0 non-null float64
Last Sold Price    0 non-null float64
Last Sold Date     0 non-null float64
Latitude           0 non-null float64
Longitude          0 non-null float64
dtypes: float64(13), object(6)
memory usage: 55.3+ MB

In [23]:
dbr1 = db[ db.zoning == 'R1' ]
dbr1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 187915 entries, 1854 to 381603
Data columns (total 19 columns):
parcelnum          187915 non-null object
address            187915 non-null object
zip_code           186962 non-null object
year_built         187915 non-null float64
zoning             187915 non-null object
land_value         187915 non-null float64
owner1             187914 non-null object
last_sale_         187915 non-null float64
last_sal_1         155998 non-null object
zEstimate          0 non-null float64
Home Type          0 non-null float64
Property Size      0 non-null float64
Home Size          0 non-null float64
Bedrooms           0 non-null float64
Bathrooms          0 non-null float64
Last Sold Price    0 non-null float64
Last Sold Date     0 non-null float64
Latitude           0 non-null float64
Longitude          0 non-null float64
dtypes: float64(13), object(6)
memory usage: 28.7+ MB

In [28]:

dbr1["last_sal_1"] = pd.to_datetime(dbr1["last_sal_1"], format = "%m/%d/%Y", errors = 'coerce')

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [30]:
dbtest = dbr1.sample(100)

In [33]:
dbtest.address = dbtest.address +', Detroit'

In [43]:
dbtest.zip_code = dbtest.zip_code.astype(int)

In [44]:
dbtest.reset_index(drop=True, inplace = True)

In [52]:
for i in range(0,len(dbtest)):
    zillow_data = ZillowWrapper('X1-ZWz1guvg85e1or_9fxlx')
    deep_search_response = zillow_data.get_deep_search_results(dbtest.address[i], dbtest.zip_code[i])
    result = GetDeepSearchResults(deep_search_response)
    dbtest.zEstimate[i] = result.zestimate_amount
    dbtest["Home Type"][i] = result.home_type
    dbtest["Property Size"][i] = result.property_size
    dbtest["Home Size"][i] = result.home_size
    dbtest["Bedrooms"][i] = result.bedrooms
    dbtest["Bathrooms"][i] = result.bathrooms
    dbtest["Last Sold Price"][i] = result.last_sold_price
    dbtest["Last Sold Date"][i] = result.last_sold_date
    dbtest["Latitude"][i] = result.latitude
    dbtest["Longitude"][i] = result.longitude

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/Users/Brenn/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

TypeError: __str__ returned non-string (type dict)

In [53]:
dbtest.head(50)

,parcelnum,address,zip_code,year_built,zoning,land_value,owner1,last_sale_,last_sal_1,zEstimate,Home Type,Property Size,Home Size,Bedrooms,Bathrooms,Last Sold Price,Last Sold Date,Latitude,Longitude
0,22119370.002,"19182 ARCHER, Detroit",48219,1955.0,R1,1162.0,"MCELROY, MARTIN L & GUANIELLE",80000.0,NaT,45725.0,SingleFamily,5445.0,1091.0,NaN,1.5,NaN,NaN,42.430466,-83.266037
1,22067899.,"8851 MEMORIAL, Detroit",48228,1947.0,R1,831.0,"GARNER, TRACY & COOK ALRICH",3000.0,NaT,18790.0,SingleFamily,5227.0,781.0,NaN,1.0,3000.0,12/01/2008,42.358782,-83.211882
2,16002636.,"5014 PACIFIC, Detroit",48204,0.0,R1,590.0,DETROIT LAND BANK AUTHORITY,65000.0,NaT,12703.0,SingleFamily,4095.0,1426.0,NaN,1.0,65000.0,02/13/2008,42.356441,-83.122018
3,13018777.,"18806 JUSTINE, Detroit",48234,0.0,R1,663.0,DETROIT LAND BANK AUTHORITY,3755.0,NaT,24815.0,SingleFamily,4879.0,880.0,NaN,1.0,99000.0,03/27/2006,42.431422,-83.058261
4,16004132.,"5614 UNDERWOOD, Detroit",48204,0.0,R1,1307.0,DETROIT LAND BANK AUTHORITY,17000.0,NaT,22295.0,SingleFamily,6316.0,960.0,NaN,1.0,NaN,None,42.361348,-83.136382
5,17016668.,"20416 BRAMFORD, Detroit",48234,1941.0,R1,572.0,"CHARLSESTON, RENEE A",26500.0,NaT,20369.0,SingleFamily,3790.0,758.0,NaN,1.0,NaN,None,42.446477,-83.023175
6,02003214.,"17166 MUIRLAND, Detroit",48221,1933.0,R1,7450.0,"THOMAS, ALFRED & BEVERLY",30000.0,NaT,317758.0,SingleFamily,6752.0,NaN,NaN,3.5,NaN,None,42.418266,-83.133644
7,21022444.,"14720 NOVARA, Detroit",48205,1930.0,R1,313.0,DETROIT LAND BANK AUTHORITY,10257.0,NaT,29990.0,SingleFamily,3136.0,1210.0,NaN,1.5,NaN,None,42.439057,-82.971144
8,17003012.,"8527 KENNEY, Detroit",48234,0.0,R1,685.0,CITY OF DETROIT - P&DD,0.0,NaT,NaN,SingleFamily,3572.0,1224.0,NaN,2.0,NaN,None,42.412118,-83.014524
9,22110989.,"14641 BENTLER, Detroit",48223,0.0,R1,702.0,DETROIT LAND BANK AUTHORITY,8000.0,NaT,20266.0,SingleFamily,4356.0,736.0,NaN,1.0,8000.0,09/04/2002,42.395209,-83.252000
10,22125322.,"4661 W OUTER DRIVE, Detroit",48235,1953.0,R1,1385.0,"JOHNSON, SHEILA R",77000.0,NaT,131097.0,SingleFamily,6752.0,2514.0,NaN,2.0,77000.0,06/01/1994,42.434358,-83.174376
11,22066785.,"16556 LINDSAY, Detroit",48235,1940.0,R1,1164.0,"RHODES, LINDA",27000.0,NaT,40093.0,SingleFamily,5401.0,1150.0,NaN,1.0,NaN,None,42.411149,-83.212646
12,21071168.,"5076 THREE MILE DR, Detroit",48224,1933.0,R1,1089.0,TAXPAYER,38000.0,NaT,43940.0,SingleFamily,4792.0,1092.0,NaN,1.0,NaN,None,42.403526,-82.940258
13,22046973.,"9923 SUSSEX, Detroit",48227,1943.0,R1,746.0,"JENKINS, BRENDA",65000.0,NaT,19081.0,SingleFamily,3790.0,800.0,NaN,1.0,65000.0,06/14/2006,42.368329,-83.194302
14,22090483.,"6886 MINOCK, Detroit",48228,1953.0,R1,598.0,CHARLENE RICHARDSON,9000.0,NaT,26681.0,SingleFamily,4356.0,821.0,NaN,1.0,NaN,None,42.342190,-83.231197
15,02002800.,"17580 FAIRWAY DR, Detroit",48221,1926.0,R1,32263.0,"LEWIS, DENISE J",0.0,NaT,341839.0,SingleFamily,24481.0,NaN,NaN,3.0,NaN,None,42.422061,-83.130685
16,22029203.,"15363 HARTWELL, Detroit",48227,1928.0,R1,935.0,"TRAVIS, TYRONE",17500.0,NaT,21503.0,SingleFamily,3964.0,918.0,NaN,1.0,NaN,None,42.403115,-83.178302
17,14006151.,"4045 DORIS, Detroit",48238,1928.0,R1,755.0,"COLLEY, RONALD LEE JR",4800.0,NaT,18057.0,SingleFamily,4008.0,668.0,4.0,1.0,4800.0,11/10/2008,42.393843,-83.137635
18,21080511.,"12255 E OUTER DRIVE, Detroit",48224,1942.0,R1,917.0,MERRICK HOUSING LLC,90416.0,NaT,52818.0,SingleFamily,4835.0,1096.0,NaN,1.0,92000.0,10/26/2006,42.405671,-82.937217
19,13023056.,"18843 KLINGER, Detroit",48234,1946.0,R1,446.0,"ARMSTRONG, TORIS",2500.0,NaT,23191.0,SingleFamily,3667.0,1000.0,3.0,1.0,2500.0,07/23/2009,42.431531,-83.069019
20,21057564.,"11831 PAYTON, Detroit",48224,1949.0,R1,1130.0,"BROWN, EARNESTINE",2000.0,NaT,51790.0,SingleFamily,5227.0,1143.0,4.0,3.0,49006.0,01/08/2004,42.422506,-82.961087
21,22105876.,"12153 BRAILE, Detroit",48228,1943.0,R1,704.0,"TAYLOR, MARCIA",4000.0,NaT,18701.0,SingleFamily,5576.0,750.0,NaN,1.0,551.0,07/24/2012,42.376178,-83.244065
22,22045431.,"15819 COYLE, Detroit",48227,1937.0,R1,891.0,"BUNNEY, MUMTAZ",19450.0,NaT,39521.0,SingleFamily,4791.0,1059.0,3.0,1.5,NaN,None,42.407418,-83.194300
23,16026726.,"13606 TULLER, Detroit",48238,0.0,R1,594.0,"DAVIS, W P & N M",14200.0,NaT,29372.0,SingleFamily,3572.0,NaN,NaN,NaN,NaN,None,42.387902,-83.146076
24,22034739.,"16800 ARDMORE, Detroit",48235,1931.0,R1,798.0,"HOWARD, STERLING",13100.0,NaT,40476.0,SingleFamily,4225.0,936.0,3.0,2.0,13100.0,01/22/2013,42.414529,-83.184678
25,16009069.008L,"8281 PEMBROKE, Detroit",48221,1972.0,R1,1923.0,"KING, CECILE P",75000.0,NaT,127385.0,SingleFamily,6534.0,1803.0,4.0,3.0,75000.0,09/11/2015,42.438358,-83.154113
26,22088219.004L,"9220 GRANDVILLE, Detroit",48228,1950.0,R1,914.0,"BAILEY, TYRONE",10000.0,NaT,25468.0,SingleFamily,6708.0,843.0,NaN,1.0,67000.0,07/28/2003,42.361842,-83.229473
27,16030783.,"16191 ROSELAWN, Detroit",48221,1928.0,R1,1153.0,ACSON LLC,59500.0,NaT,33712.0,SingleFamily,3920.0,1300.0,3.0,1.5,59500.0,03/06/2017,42.411127,-83.152424
28,22055334.,"18925 PREVOST, Detroit",48235,1939.0,R1,1012.0,DETROIT LAND BANK AUTHORITY,70000.0,NaT,72794.0,SingleFamily,5750.0,1451.0,NaN,1.0,NaN,None,42.428954,-83.204276
29,09017567.,"17613 MARX, Detroit",48203,1959.0,R1,1057.0,"HILL, ALFRED",0.0,NaT,22810.0,SingleFamily,5401.0,917.0,NaN,1.0,NaN,None,42.423518,-83.083939
30,21034023.,"18073 HAMBURG, Detroit",48205,1944.0,R1,979.0,"VAUGH, CAROL V",10000.0,NaT,64879.0,SingleFamily,174240.0,1426.0,6.0,2.0,NaN,None,42.428465,-82.997331
31,21012629.,"12155 WHITHORN, Detroit",48205,1962.0,R1,423.0,DETROIT LAND BANK AUTHORITY,17500.0,NaT,21661.0,SingleFamily,3311.0,934.0,NaN,1.0,NaN,None,42.415391,-82.992710
32,22124267.001,"16800 SALEM, Detroit",48219,1961.0,R1,701.0,"TARANOWSKI, STEPHEN & PHYLLIS",21500.0,NaT,37960.0,SingleFamily,6360.0,931.0,NaN,1.5,NaN,None,42.411925,-83.284540
33,22090127.,"9219 WESTWOOD, Detroit",48228,1950.0,R1,743.0,"JACKSON, ERVIN",24000.0,NaT,24055.0,SingleFamily,5227.0,825.0,3.0,2.0,NaN,None,42.361624,-83.231395
34,18016048.,"11789 WYOMING, Detroit",48204,0.0,R1,486.0,DETROIT LAND BANK AUTHORITY,0.0,NaT,59321.0,SingleFamily,10454.0,NaN,0.0,NaN,NaN,None,42.376166,-83.158850
35,21064779.,"10600 LAKEPOINTE, Detroit",48224,1939.0,R1,1172.0,"WEBB, CAROL D",38500.0,NaT,24723.0,SingleFamily,7405.0,905.0,NaN,1.0,38000.0,10/10/2018,42.415902,-82.954930
36,22018505.,"23093 NORFOLK, Detroit",48219,1927.0,R1,2408.0,"NIMOX, GENEVA",10000.0,NaT,53139.0,SingleFamily,13068.0,961.0,3.0,1.0,10000.0,11/20/2012,42.439720,-83.271925
37,22046301.,"16538 SUSSEX, Detroit",48235,1941.0,R1,1329.0,"GRANT, ELLANN",85000.0,NaT,41854.0,SingleFamily,5793.0,901.0,NaN,1.0,85000.0,11/05/2001,42.411835,-83.194992
38,22115500.,"13956 DACOSTA, Detroit",48223,1956.0,R1,484.0,"FORSYTHE, CLIFFORD W",0.0,NaT,23526.0,SingleFamily,4269.0,690.0,NaN,1.0,NaN,None,42.386804,-83.259641
39,21025944.,"16476 BRINGARD DR, Detroit",48205,1943.0,R1,952.0,"GILLIAM, SLINDUER DIONNE",11000.0,NaT,38369.0,SingleFamily,5227.0,713.0,2.0,1.0,16000.0,05/23/2008,42.446325,-82.949569
40,16028340.,"16156 WOODINGHAM, Detroit",48221,1928.0,R1,659.0,DETROIT LAND BANK AUTHORITY,120000.0,NaT,50144.0,SingleFamily,3485.0,1868.0,NaN,2.0,120000.0,05/19/2006,42.410683,-83.149446
41,22052418.,"14051 WINTHROP, Detroit",48227,1954.0,R1,1193.0,"SMITH, JAMES",3615.0,NaT,35781.0,SingleFamily,4356.0,978.0,2.0,1.0,NaN,None,42.389186,-83.199488
42,22010436-7,"19610 LYNDON, Detroit",48223,1941.0,R1,1187.0,"WILSON, ALONZO",20000.0,NaT,16804.0,SingleFamily,4400.0,698.0,NaN,1.0,NaN,None,42.393786,-83.235031
43,13007777.,"3908 NAUMANN, Detroit",48212,0.0,R1,3000.0,WINSTON BROS IRON & METAL CO,0.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,21031777.,"20299 WESTPHALIA, Detroit",48205,1942.0,R1,784.0,"FCN INVESTMENTS, LLC",25000.0,NaT,18167.0,SingleFamily,4966.0,722.0,NaN,1.5,14000.0,10/19/2009,42.447086,-82.993152
45,22027781.,"15498 SNOWDEN, Detroit",48227,1928.0,R1,854.0,"WILLIAMS, FLOYD M",12450.0,NaT,21508.0,SingleFamily,3790.0,1371.0,NaN,1.0,NaN,None,42.405398,-83.176715
46,22042672.,"8841 LAUDER, Detroit",48228,1949.0,R1,948.0,"THOMAS, JEANETTE",19900.0,NaT,21476.0,SingleFamily,3746.0,755.0,NaN,1.0,NaN,None,42.358996,-83.189643
47,22083291-2,"18710 STAHELIN, Detroit",48219,1942.0,R1,945.0,"MARSHALL, DAKINNA",0.0,NaT,18855.0,SingleFamily,4574.0,780.0,NaN,1.0,NaN,None,42.428372,-83.227078
48,22097651.,"13940 VAUGHAN, Detroit",48223,0.0,R1,472.0,DETROIT LAND BANK AUTHORITY,5000.0,NaT,79183.0,SingleFamily,10716.0,NaN,NaN,NaN,NaN,None,42.386936,-83.237557
49,22111469.,"20200 CHAPEL, Detroit",48219,1951.0,R1,1130.0,"SHARK ELEVEN, LLC",73000.0,NaT,39478.0,SingleFamily,435.0,803.0,3.0,1.0,42900.0,04/05/2006,42.440043,-83.254627

In [55]:
dbtest.tail(50)

,parcelnum,address,zip_code,year_built,zoning,land_value,owner1,last_sale_,last_sal_1,zEstimate,Home Type,Property Size,Home Size,Bedrooms,Bathrooms,Last Sold Price,Last Sold Date,Latitude,Longitude
50,22104988.,"9064 BRAILE, Detroit",48228,1949.0,R1,921.0,PENN STATE ENERGY LLC,0.0,NaT,27166.0,SingleFamily,6621.0,1000.0,3.0,1.0,NaN,None,42.360166,-83.242826
51,09011452-3,"18546 JOSEPH CAMPAU, Detroit",48234,1949.0,R1,974.0,"HOLLOWELL, DONNELL",65000.0,NaT,69495.0,SingleFamily,6970.0,1943.0,NaN,1.5,NaN,None,42.429014,-83.072395
52,22071872.,"14687 ARCHDALE, Detroit",48227,1929.0,R1,1100.0,"HALL, HOMER J",37500.0,NaT,52642.0,SingleFamily,5662.0,898.0,3.0,1.0,37500.0,05/04/2017,42.396862,-83.216859
53,16002940.,"5303 IVANHOE, Detroit",48204,1917.0,R1,458.0,DETROIT LAND BANK AUTHORITY,0.0,NaT,10875.0,SingleFamily,3615.0,1242.0,NaN,1.5,NaN,None,42.357097,-83.126830
54,22021471.,"18931 APPOLINE, Detroit",48235,1957.0,R1,899.0,"REED, DARRYL LARON & CASSANDRA J",32000.0,NaT,80125.0,SingleFamily,4182.0,1406.0,NaN,1.5,NaN,None,42.429939,-83.172061
55,22022965.,"14257 STEEL, Detroit",48227,1923.0,R1,458.0,DETROIT LAND BANK AUTHORITY,1500.0,NaT,19942.0,SingleFamily,4008.0,1027.0,NaN,1.0,NaN,None,42.392260,-83.171334
56,22075051-8,"15400 ASHTON, Detroit",48223,0.0,R1,3057.0,"ADAMS, CYNTHIA",179900.0,NaT,117167.0,SingleFamily,7492.0,1500.0,NaN,2.0,179900.0,09/14/2007,42.403060,-83.218985
57,16043602.,"12635 MENDOTA, Detroit",48238,1924.0,R1,394.0,"FULLER, LESLIE M",11900.0,NaT,16547.0,SingleFamily,4051.0,912.0,NaN,1.0,NaN,None,42.381187,-83.164378
58,01006284.,"150 W HILDALE, Detroit",48203,1936.0,R1,1079.0,"SECHELSKI, JAMES D",37000.0,NaT,89840.0,SingleFamily,6534.0,2000.0,4.0,2.5,35000.0,08/18/2015,42.428476,-83.105017
59,16040194.,"15058 ILENE, Detroit",48238,0.0,R1,406.0,DETROIT LAND BANK AUTHORITY,11000.0,NaT,60731.0,SingleFamily,9148.0,NaN,0.0,NaN,NaN,None,42.401125,-83.161317
60,12013044.,"15345 PETOSKEY, Detroit",48238,0.0,R1,1175.0,DETROIT LAND BANK AUTHORITY,0.0,NaT,15228.0,SingleFamily,5401.0,748.0,NaN,1.0,1292.0,04/19/2012,42.403371,-83.139387
61,09017113.,"17532 MARX, Detroit",48203,1926.0,R1,536.0,DETROIT LAND BANK AUTHORITY,0.0,NaT,17614.0,SingleFamily,3615.0,987.0,NaN,1.0,NaN,None,42.422501,-83.083176
62,22060381.,"16881 MURRAY HILL, Detroit",48235,1940.0,R1,701.0,"TUCK, DEBORAH F",23900.0,NaT,50650.0,SingleFamily,3920.0,1202.0,3.0,1.0,8000.0,07/08/2008,42.415155,-83.208137
63,22113242.,"15130 LAHSER, Detroit",48223,0.0,R1,664.0,"CHANDLER, RACHEL",0.0,NaT,58040.0,SingleFamily,4225.0,NaN,NaN,NaN,NaN,None,42.399455,-83.256278
64,22088167.,"8410 GRANDVILLE, Detroit",48228,1948.0,R1,761.0,"AIELLO, THERESA",0.0,NaT,18515.0,SingleFamily,5009.0,845.0,NaN,1.0,NaN,None,42.354278,-83.229278
65,16024542.,"9044 BRYDEN, Detroit",48204,1965.0,R1,521.0,"KITTRELL, DAVID",18000.0,NaT,12409.0,SingleFamily,3441.0,912.0,NaN,1.0,NaN,None,42.361436,-83.144713
66,16025219.,"3303 OAKMAN BLVD, Detroit",48204,1936.0,R1,1413.0,"WEATHERS, MILTON",0.0,NaT,55393.0,SingleFamily,5184.0,1600.0,NaN,1.5,NaN,None,42.382626,-83.143313
67,13022224.,"20482 NORWOOD, Detroit",48234,1941.0,R1,578.0,"RIGGINS, THEROI",26000.0,NaT,30487.0,SingleFamily,4051.0,815.0,3.0,1.0,NaN,None,42.446349,-83.067537
68,22018480.002,"22501 CHIPPEWA, Detroit",48219,1954.0,R1,1234.0,"GRIMES, TANISHA J",30000.0,NaT,58604.0,SingleFamily,5662.0,1009.0,3.0,1.0,30000.0,02/06/2017,42.438496,-83.265264
69,21008438.,"12250 WILSHIRE, Detroit",48213,1937.0,R1,972.0,"GOODSON, DAVID & LENA",15000.0,NaT,26480.0,SingleFamily,6011.0,1379.0,NaN,1.5,15000.0,06/26/2000,42.407445,-82.985159
70,13014792.,"19618 BUFFALO, Detroit",48234,1948.0,R1,575.0,"COLEMAN, DONALD",0.0,NaT,23573.0,SingleFamily,4530.0,824.0,NaN,1.5,NaN,None,42.438718,-83.047858
71,22078132.,"8257 PENROD, Detroit",48228,1942.0,R1,727.0,"KREJCI, SHERITA",16950.0,NaT,15665.0,SingleFamily,4791.0,682.0,4.0,1.0,1700.0,08/16/2013,42.353220,-83.220175
72,22055991.,"15434 RUTHERFORD, Detroit",48227,1939.0,R1,770.0,"RUTHERFORD, JACQUELINE",14500.0,NaT,43622.0,SingleFamily,4791.0,1150.0,3.0,2.0,14500.0,12/14/2016,42.403782,-83.203801
73,13015275.,"19692 BLOOM, Detroit",48234,0.0,R1,432.0,DETROIT LAND BANK AUTHORITY,0.0,NaT,30486.0,SingleFamily,3964.0,NaN,NaN,NaN,NaN,None,42.439668,-83.048966
74,22099575.,"17321 HEYDEN, Detroit",48219,1928.0,R1,443.0,"KENNETH, HANNA",6113.0,NaT,14473.0,SingleFamily,3615.0,660.0,NaN,1.0,NaN,None,42.417793,-83.240416
75,02003159.,"18215 WILDEMERE, Detroit",48221,1927.0,R1,7450.0,"WHITE, ROOSEVELT & CASENDRA",82000.0,NaT,308719.0,SingleFamily,6534.0,3100.0,5.0,3.5,120000.0,12/13/2012,42.424810,-83.133454
76,16026265.,"17398 PENNINGTON, Detroit",48221,1928.0,R1,930.0,"COSLEY, TERESA",19900.0,NaT,90853.0,SingleFamily,4356.0,1552.0,3.0,1.0,19900.0,02/07/2013,42.420343,-83.147187
77,22080956.,"7738 BRACE, Detroit",48228,0.0,R1,751.0,DETROIT LAND BANK AUTHORITY,35000.0,NaT,34154.0,SingleFamily,4966.0,892.0,NaN,1.0,35000.0,12/01/2006,42.348949,-83.222937
78,22108230.,"8285 BURT RD, Detroit",48228,1948.0,R1,789.0,DETROIT LAND BANK AUTHORITY,600.0,NaT,17880.0,SingleFamily,5227.0,806.0,NaN,1.0,1750.0,10/28/2008,42.353188,-83.245738
79,21078667.,"5544 ASHLEY, Detroit",48236,1927.0,R1,696.0,"WILSON, CONNIE",7127.0,NaT,43101.0,SingleFamily,5227.0,1000.0,2.0,1.0,7127.0,01/16/2014,42.416056,-82.917970
80,22120180.,"15701 HAZELTON, Detroit",48223,0.0,R1,552.0,"ALEXANDER, KENYATTE",23000.0,NaT,56399.0,SingleFamily,3877.0,1407.0,3.0,1.0,NaN,None,42.403942,-83.268259
81,22045113.,"18636 COYLE, Detroit",48235,1939.0,R1,1276.0,INVESTUS EXIT STRATEGY(MICHIGAN)LLC,40000.0,NaT,36744.0,SingleFamily,4791.0,990.0,2.0,1.0,40000.0,04/08/2014,42.427522,-83.194449
82,22032098.,"9655 CARLIN, Detroit",48227,0.0,R1,811.0,"NOUNKWA, CELESTIN",1000.0,NaT,29438.0,SingleFamily,4530.0,NaN,NaN,NaN,1000.0,08/19/2005,42.368021,-83.179173
83,22038955.,"14246 HUBBELL, Detroit",48227,0.0,R1,1015.0,DETROIT LAND BANK AUTHORITY,0.0,NaT,19978.0,SingleFamily,4792.0,714.0,NaN,1.0,NaN,None,42.391717,-83.188057
84,09017152.,"18062 MARX, Detroit",48203,1926.0,R1,436.0,JD HIGGINS LLC,5000.0,NaT,21006.0,SingleFamily,3615.0,1118.0,NaN,1.0,17500.0,03/12/2007,42.426166,-83.083319
85,22097634.,"13530 VAUGHAN, Detroit",48223,1954.0,R1,422.0,DETROIT LAND BANK AUTHORITY,2050.0,NaT,21136.0,SingleFamily,3398.0,686.0,NaN,1.0,NaN,None,42.384418,-83.237442
86,13024674.,"19941 GODDARD, Detroit",48234,0.0,R1,458.0,DETROIT LAND BANK AUTHORITY,24500.0,NaT,29804.0,SingleFamily,3615.0,NaN,NaN,NaN,NaN,None,42.440973,-83.077723
87,21073567.,"5112 BISHOP, Detroit",48224,1940.0,R1,740.0,"WINSTON, SHEMIKA JONAE",18500.0,NaT,71845.0,SingleFamily,4791.0,1250.0,3.0,2.0,7766.0,07/23/2012,42.406519,-82.933730
88,22125807-8,"11220 W OUTER DRIVE, Detroit",48223,0.0,R1,1077.0,MI LAND BANK FAST TRACK AUTH,1526.0,NaT,71444.0,SingleFamily,6229.0,NaN,NaN,NaN,1526.0,10/21/1997,42.398107,-83.250983
89,18014779.,"9079 NORTHLAWN, Detroit",48204,1942.0,R1,1010.0,"MATHEWS, MELVIN",30000.0,NaT,36111.0,SingleFamily,4400.0,948.0,NaN,1.0,NaN,None,42.361944,-83.152225
90,13023269.,"20466 GALLAGHER, Detroit",48234,1939.0,R1,567.0,"GOMEZ, RAYMOND KEITH",2250.0,NaT,18613.0,SingleFamily,4356.0,696.0,3.0,1.0,NaN,None,42.446101,-83.070595
91,16006424-5,"8708 DESOTO, Detroit",48238,1950.0,R1,860.0,NORTHWEST UNITY HOMES LDHA,0.0,NaT,67237.0,SingleFamily,9017.0,1296.0,3.0,1.5,NaN,None,42.401271,-83.156677
92,04002743.,"803 W BOSTON BLVD, Detroit",48202,0.0,R1,16228.0,"JOHNSON, THOMAS & ELLAZEAN",148000.0,NaT,604498.0,SingleFamily,16988.0,6200.0,7.0,6.0,148000.0,04/06/2011,42.384896,-83.090922
93,22037851.,"14934 STRATHMOOR, Detroit",48227,1936.0,R1,1062.0,"HILL, DUSAON",18000.0,NaT,36616.0,SingleFamily,4922.0,1672.0,4.0,1.0,18000.0,08/16/2007,42.398960,-83.187188
94,22112514.,"13416 GREYDALE, Detroit",48223,0.0,R1,587.0,CITY OF DETROIT-P&DD,0.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,21033161.,"19374 BARLOW, Detroit",48205,1956.0,R1,400.0,DETROIT LAND BANK AUTHORITY,32500.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,15003660-1,"6791 EDGETON, Detroit",48212,1960.0,R1,735.0,"MCCANTS, FREDERICK AND YOLANDA",18000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,22022801.,"17371 STEEL, Detroit",48235,1937.0,R1,1116.0,"MCNEAL, JIMMY",22344.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,16018874.,"13648 STOEPEL, Detroit",48238,1923.0,R1,828.0,"TANNER, R FHA 958031",0.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,17003804.,"8134 MT OLIVET, Detroit",48234,0.0,R1,445.0,DETROIT LAND BANK AUTHORITY,0.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN